# stage 1
FROM python:3.12 AS build
WORKDIR /app
COPY mkdocs-landing .
RUN  pip install --upgrade pip && pip install -r requirements.txt
RUN python -m mkdocs build

# stage 2
FROM nginx:1.15-alpine
WORKDIR /usr/share/nginx/html/
RUN rm -fr * .??*
COPY --from=build /app/site /usr/share/nginx/html