FROM dinofizz/hugo AS build

# The source files are copied to /site
COPY . /app
WORKDIR /app

RUN git submodule update --init --recursive && \
    cd www && \
    hugo --minify --enableGitInfo

# stage 2
FROM amazon/aws-cli
WORKDIR /tmp

# Clean the default public folder
RUN rm -fr * .??*

# Finally, the "public" folder generated by Hugo in the previous stage
# is copied into the public fold of nginx
COPY --from=build /app/www/public /tmp