AWSTemplateFormatVersion: 2010-09-09
Description: Static web hosting

Parameters:
  Domain:
    Type: String
  HostedZoneID:
    Type: String

Resources:

  WebSiteBucket:
    Properties:
      BucketName: !Ref Domain
    Type: AWS::S3::Bucket

  CloudFrontDistribution:
    Properties:
      DistributionConfig:
        Enabled: true
        PriceClass: PriceClass_100 # Northern America + Europe + Israel
        Aliases:
          - !Ref Domain
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:467420073914:certificate/66f04cad-92e3-46ca-ae9f-c3ed3ff5d465
          SslSupportMethod: sni-only
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt WebSiteBucket.RegionalDomainName
            OriginAccessControlId: !Ref CloudFrontOriginAccessControl
            S3OriginConfig: {}
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
    Type: AWS::CloudFront::Distribution

  CloudFrontDistributionWww:
    Properties:
      DistributionConfig:
        Enabled: true
        PriceClass: PriceClass_100 # Northern America + Europe + Israel
        Aliases:
          - !Sub www.${Domain}
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:467420073914:certificate/7a9c4d75-64cb-4900-84aa-649521f32eea
          SslSupportMethod: sni-only
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt WebSiteBucket.RegionalDomainName
            OriginAccessControlId: !Ref CloudFrontOriginAccessControl
            S3OriginConfig: {}
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
    Type: AWS::CloudFront::Distribution

  CloudFrontOriginAccessControl:
    Properties:
      OriginAccessControlConfig:
          Name: !Ref Domain
          OriginAccessControlOriginType: s3
          SigningBehavior: always
          SigningProtocol: sigv4
    Type: AWS::CloudFront::OriginAccessControl

  WebBucketPolicy:
    Properties:
      Bucket: !Ref WebSiteBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource: !Sub ${WebSiteBucket.Arn}/*
            Principal:
              Service: !Sub "cloudfront.${AWS::URLSuffix}"
            Condition:
              ArnEquals:
                "aws:SourceArn":
                  - !Sub "arn:${AWS::Partition}:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"
                  - !Sub "arn:${AWS::Partition}:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistributionWww}"
    Type: AWS::S3::BucketPolicy

  Route53RecordSetGroup:
    Properties:
      HostedZoneId: !Ref HostedZoneID
      RecordSets:
        - Name: !Ref Domain
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2 # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordsetgroup-aliastarget.html#cfn-route53-recordsetgroup-aliastarget-hostedzoneid
            DNSName: !GetAtt CloudFrontDistribution.DomainName
        - Name: !Ref Domain
          Type: AAAA
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2 # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordsetgroup-aliastarget.html#cfn-route53-recordsetgroup-aliastarget-hostedzoneid
            DNSName: !GetAtt CloudFrontDistribution.DomainName
        - Name: !Sub www.${Domain}
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2 # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordsetgroup-aliastarget.html#cfn-route53-recordsetgroup-aliastarget-hostedzoneid
            DNSName: !GetAtt CloudFrontDistributionWww.DomainName
        - Name: !Sub www.${Domain}
          Type: AAAA
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2 # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordsetgroup-aliastarget.html#cfn-route53-recordsetgroup-aliastarget-hostedzoneid
            DNSName: !GetAtt CloudFrontDistributionWww.DomainName
    Type: AWS::Route53::RecordSetGroup

Outputs:
  CloudFrontUrl:
    Value: !GetAtt CloudFrontDistribution.DomainName
  CloudFrontUrlWww:
    Value: !GetAtt CloudFrontDistributionWww.DomainName